package motobikeshop;


import entities.HangXe;
import entities.XeMay;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinhp
 */
public class QuanLiDanhMuc extends javax.swing.JPanel {
    /**
     * Creates new form QuanLiDanhMuc
     */
    public QuanLiDanhMuc() {
        initComponents();
        LoadDataHX();
        LoadDataXe("Tất cả");
    }
    
    public void LoadDataHX(){
        DefaultTableModel dtm = (DefaultTableModel) tblHX.getModel();
        dtm.setNumRows(0);
        for(HangXe hx : HangXe.findAll()){
            dtm.addRow(new Object[]{ hx.getMaHX(), hx.getTenHX()});
        }
        this.tblHX.setModel(dtm);
    }
    
    public void LoadDataXe(String choose){
        DefaultTableModel dtm = (DefaultTableModel) tblXe.getModel();
        dtm.setNumRows(0);
        
        if(choose.equals("Tất cả")){
                for(XeMay xe : XeMay.findAll()){
                dtm.addRow(new Object[]{ xe.getMaXe(), xe.getTenXe(), xe.getMaHX(), xe.getSoLuong(), xe.getGiaNhap(),
                xe.getGiaBan(), xe.getPhanKhoi()});
            }
        }
        else{
            for(XeMay xe : XeMay.findByHX(choose)){
            dtm.addRow(new Object[]{ xe.getMaXe(), xe.getTenXe(), xe.getMaHX(), xe.getSoLuong(), xe.getGiaNhap(),
            xe.getGiaBan(), xe.getPhanKhoi()});
        }
        }

        this.tblXe.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHX = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblXe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMaHX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHX = new javax.swing.JTextField();
        btnThemHX = new javax.swing.JButton();
        btnSuaHX = new javax.swing.JButton();
        btnXoaHX = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPhanKhoi = new javax.swing.JTextField();
        btnThemXe = new javax.swing.JButton();
        btnSuaXe = new javax.swing.JButton();
        btnXoaXe = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel7.setText("Số lượng:");

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblHX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Hãng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHXMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHX);
        if (tblHX.getColumnModel().getColumnCount() > 0) {
            tblHX.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        tblXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên xe", "Mã hãng", "SL", "Giá nhập", "Giá bán", "Phân khối"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblXe);
        if (tblXe.getColumnModel().getColumnCount() > 0) {
            tblXe.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblXe.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblXe.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblXe.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblXe.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblXe.getColumnModel().getColumn(6).setPreferredWidth(45);
        }

        jLabel1.setText("Mã hãng:");

        jLabel2.setText("Tên hãng:");

        btnThemHX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btnThemHX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHXActionPerformed(evt);
            }
        });

        btnSuaHX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btnSuaHX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHXActionPerformed(evt);
            }
        });

        btnXoaHX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoaHX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHXActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã xe:");

        jLabel4.setText("Tên xe:");

        jLabel5.setText("Mã hãng:");

        jLabel6.setText("Số lượng:");

        jLabel8.setText("Giá nhập:");

        jLabel9.setText("Giá bán:");

        jLabel10.setText("Phân khối");

        btnThemXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btnThemXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXeActionPerformed(evt);
            }
        });

        btnSuaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btnSuaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaXeActionPerformed(evt);
            }
        });

        btnXoaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXeActionPerformed(evt);
            }
        });

        jLabel11.setText("Hãng:");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenHX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemHX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuaHX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaHX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPhanKhoi, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSL))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemXe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(txtPhanKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenHX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuaHX)
                            .addComponent(btnThemHX)
                            .addComponent(btnXoaHX)
                            .addComponent(btnSuaXe)
                            .addComponent(btnThemXe)
                            .addComponent(btnXoaXe)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHXActionPerformed
        HangXe hx = new HangXe();
        hx.setMaHX(txtMaHX.getText());
        hx.setTenHX(txtTenHX.getText());
        
        HangXe.insertHX(hx);
        LoadDataHX();
    }//GEN-LAST:event_btnThemHXActionPerformed

    private void tblXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXeMouseClicked
        try{
            int id = tblXe.getSelectedRow();
            
            txtMaXe.setText(tblXe.getValueAt(id,0).toString());
            txtTenXe.setText(tblXe.getValueAt(id,1).toString());
            txtMaHang.setText(tblXe.getValueAt(id,2).toString());
            txtSL.setText(tblXe.getValueAt(id,3).toString());
            txtGiaNhap.setText(tblXe.getValueAt(id,4).toString());
            txtGiaBan.setText(tblXe.getValueAt(id,5).toString());
            txtPhanKhoi.setText(tblXe.getValueAt(id,6).toString());
            
        }catch(Exception e){
        }
    }//GEN-LAST:event_tblXeMouseClicked

    private void tblHXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHXMouseClicked
        try{
            int id = tblHX.getSelectedRow();
            String maHX = tblHX.getValueAt(id,0).toString();
            String tenHX = tblHX.getValueAt(id, 1).toString();
            
            txtMaHX.setText(maHX);
            txtTenHX.setText(tenHX);
        }catch(Exception e){
        }
    }//GEN-LAST:event_tblHXMouseClicked

    private void btnXoaHXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHXActionPerformed
        try{
            int id = tblHX.getSelectedRow();
            String maHX = tblHX.getValueAt(id,0).toString();
            String tenHX = tblHX.getValueAt(id, 1).toString();
            
            txtMaHX.setText(maHX);
            txtTenHX.setText(tenHX);
            HangXe.deleteHX(txtMaHX.getText());
            LoadDataHX();
        }catch(Exception e){
        }
    }//GEN-LAST:event_btnXoaHXActionPerformed

    private void btnSuaHXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHXActionPerformed
        HangXe hx = new HangXe();
        hx.setMaHX(txtMaHX.getText());
        hx.setTenHX(txtTenHX.getText());
        
        HangXe.updateHX(hx);
        LoadDataHX();
    }//GEN-LAST:event_btnSuaHXActionPerformed

    private void btnThemXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXeActionPerformed
        XeMay xe = new XeMay();
        xe.setMaXe(txtMaXe.getText());
        xe.setTenXe(txtTenXe.getText());
        xe.setSoLuong(Integer.parseInt(txtSL.getText()));
        xe.setMaHX(txtMaHang.getText());
        xe.setGiaBan(Integer.parseInt(txtGiaBan.getText()));
        xe.setGiaNhap(Integer.parseInt(txtGiaNhap.getText()));
        xe.setPhanKhoi(txtPhanKhoi.getText());
        
        XeMay.insertXe(xe);
        LoadDataXe(txtMaHang.getText());
        
        String tenHX=null;
        for(HangXe hx : HangXe.findAll()){
                if(hx.getMaHX().equals(xe.getMaHX())){
                    tenHX = hx.getTenHX();
                }
            }
        jComboBox1.setSelectedItem(tenHX);
    }//GEN-LAST:event_btnThemXeActionPerformed

    private void btnSuaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaXeActionPerformed
        XeMay xe = new XeMay();
        xe.setMaXe(txtMaXe.getText());
        xe.setTenXe(txtTenXe.getText());
        xe.setSoLuong(Integer.parseInt(txtSL.getText()));
        xe.setMaHX(txtMaHang.getText());
        xe.setGiaBan(Integer.parseInt(txtGiaBan.getText()));
        xe.setGiaNhap(Integer.parseInt(txtGiaNhap.getText()));
        xe.setPhanKhoi(txtPhanKhoi.getText());
        
        XeMay.updateXe(xe);
        LoadDataXe(txtMaHang.getText());
        
        String tenHX=null;
        for(HangXe hx : HangXe.findAll()){
                if(hx.getMaHX().equals(xe.getMaHX())){
                    tenHX = hx.getTenHX();
                }
            }
        jComboBox1.setSelectedItem(tenHX);
    }//GEN-LAST:event_btnSuaXeActionPerformed

    private void btnXoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXeActionPerformed
        String maXe = txtMaXe.getText();

        XeMay.deleteXe(maXe);
        LoadDataXe("Tất cả");
    }//GEN-LAST:event_btnXoaXeActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultComboBoxModel  model = new DefaultComboBoxModel ();
        model.addElement("Tất cả");
        for(HangXe hx : HangXe.findAll()){
            model.addElement(hx.getTenHX());
        }
        jComboBox1.setModel(model);
    }//GEN-LAST:event_formComponentShown

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedItem().toString().equals("Tất cả"))
        {
            LoadDataXe("Tất cả");
        }
        else{
            String maHX=null;
            for(HangXe hx : HangXe.findAll()){
                if(hx.getTenHX().equals(jComboBox1.getSelectedItem().toString())){
                    maHX = hx.getMaHX();
                }
            }
            LoadDataXe(maHX);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaHX;
    private javax.swing.JButton btnSuaXe;
    private javax.swing.JButton btnThemHX;
    private javax.swing.JButton btnThemXe;
    private javax.swing.JButton btnXoaHX;
    private javax.swing.JButton btnXoaXe;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblHX;
    private javax.swing.JTable tblXe;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaHX;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtPhanKhoi;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenHX;
    private javax.swing.JTextField txtTenXe;
    // End of variables declaration//GEN-END:variables
}
