/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motobikeshop;

import entities.ConnectDB;
import entities.HangXe;
import entities.XeMay;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhp
 */
public class ThongKeBaoCao extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeBaoCao
     */
    public ThongKeBaoCao() {
        initComponents();
        BaoCao1();
        BaoCao2();
    }
    
    public void BaoCao1(){
        DefaultTableModel dtm = (DefaultTableModel) tblBaoCao1.getModel();
        dtm.setNumRows(0);
        for(XeMay xe : XeMay.findBySL()){
            dtm.addRow(new Object[]{ xe.getMaXe(), xe.getTenXe(), xe.getMaHX(), xe.getSoLuong(), xe.getGiaNhap(),
                xe.getGiaBan(), xe.getPhanKhoi()});
        }
        this.tblBaoCao1.setModel(dtm);
    }
    
    public void BaoCao2(){
        DefaultTableModel dtm = (DefaultTableModel) tblBaoCao2.getModel();
        dtm.setNumRows(0);
        Connection conn = ConnectDB.createCon();
        Statement statement = null;
        
        try{          
            String sql = "select xe.*, sum(ct.SOLUONG) as sldaban from XE xe, HOADON hd, CTHD ct \n"
                    + "where xe.MAXE = ct.MAXE and hd.MAHD = ct.MAHD and\n"
                    + "cast(strftime('%m', NGAYLAP) as Integer) =  (cast(strftime('%m', 'now') as Integer) - 1) \n"
                    + "group by xe.MAXE order by sldaban desc";
            statement = conn.createStatement();
            
            ResultSet rs = statement.executeQuery(sql);
            int i = 0;
            while(rs.next()){
                i++;
                if(i>3)
                    break;
                dtm.addRow(new Object[]{rs.getString(1), rs.getString(2),rs.getString(3), rs.getInt(8), rs.getInt(5),
                rs.getInt(6), rs.getString(7)}); 
            }
            this.tblBaoCao2.setModel(dtm);
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        
        if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                }
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBaoCao1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxThang = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDoanhThu = new javax.swing.JLabel();
        txtLoiNhuan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBaoCao2 = new javax.swing.JTable();

        jLabel1.setText("Các mặt hàng sắp hết");

        tblBaoCao1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Tên xe", "Mã hãng", "Số lượng", "Giá nhập", "Giá bán", "Phân khối"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBaoCao1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(428, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Các mặt hàng bán chạy trong tháng trước(Top3)");

        jLabel3.setText("Doanh thu, lợi nhuận của tháng");

        jComboBoxThang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBoxThang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxThangItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tổng doanh thu:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tổng lợi nhuận  :");

        txtDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDoanhThu.setForeground(new java.awt.Color(255, 0, 0));
        txtDoanhThu.setText("0");

        txtLoiNhuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLoiNhuan.setForeground(new java.awt.Color(255, 0, 51));
        txtLoiNhuan.setText("0");

        tblBaoCao2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Tên xe", "Mã hãng", "SL đã bán", "Giá nhập", "Giá bán", "Phân khối"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblBaoCao2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDoanhThu))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBoxThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtLoiNhuan)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDoanhThu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLoiNhuan))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxThangItemStateChanged
        String sqlString = "select sum(ct.SOLUONG)*(xe.GIABAN) as doanhthu, sum(ct.SOLUONG)*(xe.GIABAN - xe.GIANHAP) as loinhuan\n" +
                           "from HOADON as hd, CTHD as ct, XE as xe\n" +
                            "where hd.MAHD = ct.MAHD and ct.MAXE = xe.MAXE and\n" +
                            "cast(strftime('%m', hd.NGAYLAP) as Integer) = ?";
        Connection conn = ConnectDB.createCon();
        Statement statement = null;
        
        try{
            PreparedStatement pres = conn.prepareStatement(sqlString);
            pres.setString(1, jComboBoxThang.getSelectedItem().toString());
            
            ResultSet rs = pres.executeQuery();
            if(rs.getString(1) == null){
                txtDoanhThu.setText("0");
                txtLoiNhuan.setText("0");
            }else{
                txtDoanhThu.setText(rs.getString(1));
                txtLoiNhuan.setText(rs.getString(2));
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        
        if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                }
            }
                
    }//GEN-LAST:event_jComboBoxThangItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblBaoCao1;
    private javax.swing.JTable tblBaoCao2;
    private javax.swing.JLabel txtDoanhThu;
    private javax.swing.JLabel txtLoiNhuan;
    // End of variables declaration//GEN-END:variables
}
